### ISSUE TITLE
ModuleNotFoundError: No module named 'cgi'

### ISSUE THREAD

**Issue by chbeer** [borrrrring/xcstrings#6]
After running `pip3 install -r requirements.txt` the script reports:

```
Traceback (most recent call last):
  File "/Users/christian/Downloads/xcstrings-main/xcstrings.py", line 7, in <module>
    from googletrans import Translator
  File "/opt/homebrew/lib/python3.13/site-packages/googletrans/__init__.py", line 6, in <module>
    from googletrans.client import Translator
  File "/opt/homebrew/lib/python3.13/site-packages/googletrans/client.py", line 13, in <module>
    import httpx
  File "/opt/homebrew/lib/python3.13/site-packages/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/opt/homebrew/lib/python3.13/site-packages/httpx/_api.py", line 3, in <module>
    from ._client import Client, StreamContextManager
  File "/opt/homebrew/lib/python3.13/site-packages/httpx/_client.py", line 8, in <module>
    from ._auth import Auth, BasicAuth, FunctionAuth
  File "/opt/homebrew/lib/python3.13/site-packages/httpx/_auth.py", line 10, in <module>
    from ._models import Request, Response
  File "/opt/homebrew/lib/python3.13/site-packages/httpx/_models.py", line 1, in <module>
    import cgi
ModuleNotFoundError: No module named 'cgi'
```

**Comment by borrrrring** [comment]
The root cause of this error is that the cgi module has been completely removed in Python 3.13 (it was deprecated in Python 3.11). The httpx package, which is a dependency of googletrans==4.0.0rc1, contains some code that relies on the cgi module.

Here are solutions to resolve this issue:

Solution 1: Downgrade Python Version

Since googletrans==4.0.0rc1 is incompatible with Python 3.13, it’s recommended to downgrade to Python 3.11 or 3.10. Follow these steps:
	1.	Install a compatible Python version:

brew install python@3.11


	2.	Use the specific Python version to run your script:

python3.11 -m pip install -r requirements.txt
python3.11 xcstrings.py

Solution 2: Modify httpx Source Code

If you must use Python 3.13, you can manually patch the httpx code to remove its dependency on the cgi module:
	1.	Open the httpx/_models.py file:

vi /opt/homebrew/lib/python3.13/site-packages/httpx/_models.py


	2.	Locate and remove the following line:

import cgi


	3.	Replace all usages of cgi. For example:

content_type, options = cgi.parse_header(headers["Content-Type"])

Replace it with:

content_type, options = headers["Content-Type"].split(";")[0], {}

Solution 3: Use an Alternative Library

The googletrans==4.0.0rc1 library has been unmaintained for a while. Consider using a more modern alternative:
	1.	Install the googletrans-new package:

pip install googletrans==4.0.0-rc1 --upgrade

Or try a popular community-driven alternative:

pip install google-trans-new

Verify Compatibility and Retry

Run the following command to verify that all dependencies are properly installed:

pip check

Then, rerun your script:

python xcstrings.py
